events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html/public;

        location /config.js {
            alias /config_data/config.js;
            add_header Content-Type application/javascript;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
