services:
  server:
    build:
      context: ./server
    container_name: galacticgamble-server
    environment: 
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules    # evita sobrescribir node_modules dentro del contenedor
    command: npm run dev

  frontend:
    build: ./frontend
    environment:
      - WS_HOST=192.168.0.99
      - WS_PORT=8080
    ports:
      - "3000:80"
    container_name: galacticgamble-front
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - config_data:/config_data
    depends_on:
      - server


volumes:
  config_data: