services:
  server:
    build:
      context: ./server
    container_name: galacticgamble-server
    environment: 
      - NODE_ENV=development
      - HOST=${HOST}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./server:/app
      - /app/node_modules 
    command: npm run dev

  frontend:
    build: ./frontend
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
    ports:
      - "${CLIENT_PORT}:80"
    container_name: galacticgamble-front
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - config_data:/config_data
    depends_on:
      - server


volumes:
  config_data: